//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource.ResourceFiles {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HttpResponseMessages_fa {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HttpResponseMessages_fa() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resource.ResourceFiles.HttpResponseMessages.fa", typeof(HttpResponseMessages_fa).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انجام شد..
        /// </summary>
        internal static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره تماس موجود می باشد..
        /// </summary>
        internal static string DuplicatePhoneNumber {
            get {
                return ResourceManager.GetString("DuplicatePhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل یا شماره تماس موجود می باشد..
        /// </summary>
        internal static string DuplicatePhoneNumberOrEmail {
            get {
                return ResourceManager.GetString("DuplicatePhoneNumberOrEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محتوای رسانه خالی است..
        /// </summary>
        internal static string EmptyMedia {
            get {
                return ResourceManager.GetString("EmptyMedia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این فرمت فایل پشتیبانی نمی شود..
        /// </summary>
        internal static string ExtensionNotSupported {
            get {
                return ResourceManager.GetString("ExtensionNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور نادرست است..
        /// </summary>
        internal static string IncorrectPassword {
            get {
                return ResourceManager.GetString("IncorrectPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رفرش توکن نادرست است..
        /// </summary>
        internal static string IncorrectRefreshToken {
            get {
                return ResourceManager.GetString("IncorrectRefreshToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محتوا پیدا نشد..
        /// </summary>
        internal static string MediaContentNotFound {
            get {
                return ResourceManager.GetString("MediaContentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محتوا منقضی شده است..
        /// </summary>
        internal static string MediaExpired {
            get {
                return ResourceManager.GetString("MediaExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محتوای این مدیا تایید نشده است..
        /// </summary>
        internal static string MediaNotVerified {
            get {
                return ResourceManager.GetString("MediaNotVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرداخت قبلا پردازش شده است..
        /// </summary>
        internal static string PaymentAlreadyProcessed {
            get {
                return ResourceManager.GetString("PaymentAlreadyProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرداخت قبلا تایید شده است..
        /// </summary>
        internal static string PaymentAlreadyVerified {
            get {
                return ResourceManager.GetString("PaymentAlreadyVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرداخت منقضی شده است. مبلغ به حساب شما بازگشت داده میشود..
        /// </summary>
        internal static string PaymentExpired {
            get {
                return ResourceManager.GetString("PaymentExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بارکد پیدا نشد..
        /// </summary>
        internal static string QrCodeNotFound {
            get {
                return ResourceManager.GetString("QrCodeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سرویس پیدا نشد..
        /// </summary>
        internal static string ServiceNotFound {
            get {
                return ResourceManager.GetString("ServiceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نشست شما به منقضی شده است..
        /// </summary>
        internal static string SessionExpired {
            get {
                return ResourceManager.GetString("SessionExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما اجازه دسترسی به محتوای خواسته شده را ندارید..
        /// </summary>
        internal static string Unauthorized {
            get {
                return ResourceManager.GetString("Unauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطایی غیر منتظره رخ داده است..
        /// </summary>
        internal static string UnhandledException {
            get {
                return ResourceManager.GetString("UnhandledException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر پیدا نشد..
        /// </summary>
        internal static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سایز فایل از سایز محتوا بیشتر است..
        /// </summary>
        internal static string ViolationOfMediaMaxSize {
            get {
                return ResourceManager.GetString("ViolationOfMediaMaxSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرداخت اشتباه است..
        /// </summary>
        internal static string WrongPayment {
            get {
                return ResourceManager.GetString("WrongPayment", resourceCulture);
            }
        }
    }
}
